FROM node:14.16.0-alpine3.13 as build
WORKDIR /frontend
ENV PATH /app/node_modules/.bin:$PATH
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci
COPY ./frontend ./
RUN npm run build
RUN rm -rf node_modules

FROM nginx:stable-alpine
COPY --from=build /frontend/build /usr/share/nginx/html/frontend

CMD ["nginx", "-g", "daemon off;"]
