FROM node:14.16.0-alpine3.13 as build
WORKDIR /backend
ENV PATH /app/node_modules/.bin:$PATH
COPY ./backend/package.json ./
COPY ./backend/package-lock.json ./
RUN npm ci
COPY ./backend ./
RUN npm run build:socket
RUN rm -rf node_modules

FROM node:14.16.0-alpine3.13
WORKDIR /backend
COPY --from=build /backend/dist/dist.socket ./
RUN npm ci --production
CMD ["node", "./src/socket/index.js"]
