export const registeredUserRoles = {
  ADMIN: 1,
  DJ: 2
};

export const permissions = {
  SONGS_SEARCH: 'SONGS_SEARCH',
  CREATE_LIBRARY: 'CREATE_LIBRARY',
  DELETE_LIBRARY: 'DELETE_LIBRARY',
  UPDATE_LIBRARY: 'UPDATE_LIBRARY',
  GET_LIBRARY_BY_ID: 'GET_LIBRARY_BY_ID',
  GET_LIBRARIES: 'GET_LIBRARIES',
  IMPORT_SONGS_FROM_ITUNES: 'IMPORT_SONGS_FROM_ITUNES',
  DELETE_SONGS_FROM_ITUNES: 'DELETE_SONGS_FROM_ITUNES',
  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  UPDATE_USER: 'UPDATE_USER',
  CHECK_USER_EXISTS: 'CHECK_USER_EXISTS',
  CREATE_ROOM_USER: 'CREATE_ROOM_USER',
  GET_ALL_ROOMS: 'GET_ALL_ROOMS',
  GET_ROOM_BY_ID: 'GET_ROOM_BY_ID',
  CREATE_ROOM: 'CREATE_ROOM',
  DELETE_ROOM: 'DELETE_ROOM',
  ADD_LIBRARY_TO_ROOM: 'ADD_LIBRARY_TO_ROOM',
  DELETE_LIBRARY_FROM_ROOM: 'DELETE_LIBRARY_FROM_ROOM',
  ADD_MODERATOR_TO_ROOM: 'ADD_MODERATOR_TO_ROOM',
  DELETE_MODERATOR_FROM_ROOM: 'DELETE_MODERATOR_FROM_ROOM'
};

export const roomUserPermissions = [
  permissions.SONGS_SEARCH,
  permissions.CREATE_ROOM_USER
];

export const adminPermissions = [
  permissions.CREATE_LIBRARY,
  permissions.DELETE_LIBRARY,
  permissions.UPDATE_LIBRARY,
  permissions.GET_LIBRARY_BY_ID,
  permissions.GET_LIBRARIES,
  permissions.IMPORT_SONGS_FROM_ITUNES,
  permissions.DELETE_SONGS_FROM_ITUNES,
  permissions.CREATE_USER,
  permissions.DELETE_USER,
  permissions.GET_ALL_USERS,
  permissions.UPDATE_USER,
  permissions.CHECK_USER_EXISTS,
  permissions.CREATE_ROOM_USER,
  permissions.GET_ALL_ROOMS,
  permissions.GET_ROOM_BY_ID,
  permissions.CREATE_ROOM,
  permissions.DELETE_ROOM,
  permissions.ADD_LIBRARY_TO_ROOM,
  permissions.DELETE_LIBRARY_FROM_ROOM,
  permissions.ADD_MODERATOR_TO_ROOM,
  permissions.DELETE_MODERATOR_FROM_ROOM
];

export const djPermissions = [

];
