export const registeredUserRoles = {
  ADMIN: 1,
  DJ: 2
};

export const permissions = {
  PAGE_DASHBOARD: 'PAGE_DASHBOARD',
  PAGE_ROOMS_DASHBOARD: 'PAGE_ROOMS_DASHBOARD',
  PAGE_MANAGE_ROOM_LIBRARIES: 'PAGE_MANAGE_ROOM_LIBRARIES',
  PAGE_LIBRARIES_DASHBOARD: 'PAGE_LIBRARIES_DASHBOARD',
  PAGE_USERS_DASHBOARD: 'PAGE_USERS_DASHBOARD',
  PAGE_MAKE_A_SONG_REQUEST: 'PAGE_MAKE_A_SONG_REQUEST',
  PAGE_RECOMMEND_SONG: 'PAGE_RECOMMEND_SONG',
  PAGE_ROOM: 'PAGE_ROOM',
  PAGE_SONG_REQUEST: 'PAGE_SONG_REQUEST',
  PAGE_MANAGE_ROOM_MODERATORS: 'PAGE_MANAGE_ROOM_MODERATORS',
  PAGE_MODERATE_ROOMS: 'PAGE_MODERATE_ROOMS',
  PAGE_MODERATE_ROOM: 'PAGE_MODERATE_ROOM',
  SONGS_SEARCH: 'SONGS_SEARCH',
  CREATE_LIBRARY: 'CREATE_LIBRARY',
  DELETE_LIBRARY: 'DELETE_LIBRARY',
  UPDATE_LIBRARY: 'UPDATE_LIBRARY',
  GET_LIBRARY_BY_ID: 'GET_LIBRARY_BY_ID',
  GET_LIBRARIES: 'GET_LIBRARIES',
  IMPORT_SONGS: 'IMPORT_SONGS',
  DELETE_SONGS: 'DELETE_SONGS',
  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
  CHECK_USER_EXISTS: 'CHECK_USER_EXISTS',
  GET_ALL_ROOMS: 'GET_ALL_ROOMS',
  GET_ROOM_BY_ID: 'GET_ROOM_BY_ID',
  GET_ROOM_QR: 'GET_ROOM_QR',
  CREATE_ROOM: 'CREATE_ROOM',
  DELETE_ROOM: 'DELETE_ROOM',
  ADD_LIBRARY_TO_ROOM: 'ADD_LIBRARY_TO_ROOM',
  DELETE_LIBRARY_FROM_ROOM: 'DELETE_LIBRARY_FROM_ROOM',
  ADD_MODERATOR_TO_ROOM: 'ADD_MODERATOR_TO_ROOM',
  DELETE_MODERATOR_FROM_ROOM: 'DELETE_MODERATOR_FROM_ROOM'
};

export const roomUserPermissions = [
  permissions.PAGE_MAKE_A_SONG_REQUEST,
  permissions.PAGE_RECOMMEND_SONG,
  permissions.PAGE_SONG_REQUEST,
  permissions.SONGS_SEARCH
];

export const adminPermissions = [
  permissions.PAGE_DASHBOARD,
  permissions.PAGE_ROOMS_DASHBOARD,
  permissions.PAGE_MANAGE_ROOM_LIBRARIES,
  permissions.PAGE_LIBRARIES_DASHBOARD,
  permissions.PAGE_USERS_DASHBOARD,
  permissions.PAGE_MANAGE_ROOM_MODERATORS,
  permissions.PAGE_MODERATE_ROOMS,
  permissions.PAGE_MODERATE_ROOM,
  permissions.CREATE_LIBRARY,
  permissions.DELETE_LIBRARY,
  permissions.UPDATE_LIBRARY,
  permissions.GET_LIBRARY_BY_ID,
  permissions.GET_LIBRARIES,
  permissions.IMPORT_SONGS,
  permissions.DELETE_SONGS,
  permissions.CREATE_USER,
  permissions.DELETE_USER,
  permissions.GET_ALL_USERS,
  permissions.UPDATE_USER_ROLE,
  permissions.CHECK_USER_EXISTS,
  permissions.GET_ALL_ROOMS,
  permissions.GET_ROOM_BY_ID,
  permissions.CREATE_ROOM,
  permissions.DELETE_ROOM,
  permissions.ADD_LIBRARY_TO_ROOM,
  permissions.DELETE_LIBRARY_FROM_ROOM,
  permissions.ADD_MODERATOR_TO_ROOM,
  permissions.DELETE_MODERATOR_FROM_ROOM,
  permissions.GET_ROOM_QR
];

export const djPermissions = [
  permissions.PAGE_DASHBOARD,
  permissions.PAGE_MODERATE_ROOMS,
  permissions.PAGE_MODERATE_ROOM
];
