export const CLIENT__ADD_SONG_REQUEST = 'CLIENT__ADD_SONG_REQUEST';
export const CLIENT__GET_SONG_REQUESTS = 'CLIENT__GET_SONG_REQUESTS';
export const CLIENT__DELETE_SONG_REQUEST = 'CLIENT__DELETE_SONG_REQUEST';
