# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-2mixx-dev-weu-001

# env:
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: './frontend'

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Configure environment variables
        uses: azure/appservice-settings@v1
        with:
          app-name: app-2mixx-dev-weu-001
          mask-inputs: false
          app-settings-json: '[{ "name": "REACT_APP_API_BASE_URL", "value": "https://api-2mixx-dev-weu-001.azurewebsites.net/api", "slotSetting": false }, { "name": "REACT_APP_AUTH0_CLIENT_ID", "value": "zYDA024SwEGuAXzgRA7jiqpo1mpQHvrW", "slotSetting": false }, { "name": "REACT_APP_AUTH0_DOMAIN", "value": "dev-yhhleh3j.us.auth0.com", "slotSetting": false }, { "name": "REACT_APP_SOCKET_BASE_URI", "value": "wss://socket-2mixx-dev-weu-001.azurewebsites.net", "slotSetting": false }]'
        id: settings
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: frontend/build

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-2mixx-dev-weu-001'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3763041C7614862A39EB9D0F728DA25 }}
          package: .
